import { useEffect, useRef, useState } from 'react';
import { upload } from '@vercel/blob/client';
import { ArrowUpRight, ClipboardCheck, Database, FileUp, Fingerprint, LineChart, LockKeyhole, LogOut, ShieldAlert, UploadCloud } from 'lucide-react';
import { createUserWithEmailAndPassword, onAuthStateChanged, signInWithEmailAndPassword, signOut } from 'firebase/auth';
import { auth, firebaseConfigured } from './firebase';
import { apiFetch } from './api';
import ReviewDashboard from './ReviewDashboard';

const MAX_UPLOAD_BYTES = 500 * 1024 * 1024;
const ATTACKS = [['DDoS', 'Volumetric & protocol floods'], ['Phishing', 'Credential theft & BEC'], ['Malware', 'Payload & execution traces'], ['Brute Force', 'Credential abuse attempts'], ['Multi-Vector', 'Cross-signal investigation']];

function ModernLogin() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [mode, setMode] = useState('signin'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(event) { event.preventDefault(); if (!firebaseConfigured || !auth) { setError('Firebase is not configured.'); return; } setBusy(true); setError(''); try { if (mode === 'signup') await createUserWithEmailAndPassword(auth, email, password); else await signInWithEmailAndPassword(auth, email, password); } catch (authError) { setError(authError.code?.replace('auth/', '').replaceAll('-', ' ') || 'Authentication failed.'); } finally { setBusy(false); } }
  return <main className="login-screen"><div className="login-mark"><ShieldAlert size={21} /> CTI / ANCHOR</div><section className="login-panel"><div className="eyebrow">SECURE OPERATIONS CONSOLE <span>v1.0</span></div><h1>Make threat<br /><em>evidence</em> permanent.</h1><p className="muted">Analyze incident data, fingerprint sensitive evidence, and anchor verified reports to an immutable ledger.</p><form className="login-fields" onSubmit={submit}><label>WORK EMAIL<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label>PASSWORD<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} minLength="6" required /></label>{error && <p className="form-error">{error}</p>}<button className="primary full" disabled={busy}>{busy ? 'Authenticating...' : mode === 'signup' ? 'Create account' : 'Enter workspace'} <ArrowUpRight size={16} /></button></form><button className="auth-switch" onClick={() => setMode(mode === 'signin' ? 'signup' : 'signin')}>{mode === 'signin' ? 'Create a new account' : 'Already have an account? Sign in'}</button><div className="login-foot"><LockKeyhole size={14} /> Firebase Authentication · Secure session</div></section><div className="login-orbit"><div className="orbit-core"><Fingerprint size={40} /><strong>SHA-256</strong><small>TRUST LAYER</small></div></div></main>;
}

function ProcessEvidencePage() {
  const [attack, setAttack] = useState('DDoS'); const [file, setFile] = useState(null); const [org, setOrg] = useState(''); const [result, setResult] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function submit(event) { event.preventDefault(); if (!file || !org.trim()) { setError('Organization name and a CSV dataset are required.'); return; } if (file.size > MAX_UPLOAD_BYTES) { setError('This CSV is larger than 500 MB.'); return; } setBusy(true); setError(''); try { const blob = await upload(file.name, file, { access: 'private', handleUploadUrl: '/api/upload' }); const form = new FormData(); form.append('org_name', org); form.append('attack_type', attack); form.append('dataset_url', blob.url); form.append('filename', file.name); const response = await apiFetch('/api/threat/process-and-anchor-url', { method: 'POST', body: form }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || 'Processing failed'); setResult(payload); } catch (requestError) { setError(requestError.message); } finally { setBusy(false); } }
  return <section className="process-grid"><form className="form-panel" onSubmit={submit}><div className="panel-title"><span>01</span><div><h3>Configure investigation</h3><p>Submit evidence for administrator review.</p></div></div><label>ORGANIZATION NAME<input value={org} onChange={(event) => setOrg(event.target.value)} placeholder="e.g. Northstar Security" /></label><label>SUBMITTER CONTACT / ROLE<input defaultValue="SOC Operator" /></label><div className="label-row"><span>ATTACK VECTOR</span><span className="required">REQUIRED</span></div><div className="attack-grid">{ATTACKS.map(([name, note]) => <button type="button" key={name} className={`attack-option ${attack === name ? 'selected' : ''}`} onClick={() => setAttack(name)}><span className="attack-dot" /><strong>{name}</strong><small>{note}</small></button>)}</div><label className="dropzone"><input type="file" accept=".csv,text/csv" onChange={(event) => setFile(event.target.files?.[0])} /><div className="upload-icon"><UploadCloud size={24} /></div><strong>{file ? file.name : 'Drop incident CSV here'}</strong><span>{file ? `${(file.size / 1024).toFixed(1)} KB ready for analysis` : 'or click to browse · max 500 MB per file'}</span></label><button className="primary submit" disabled={busy}>{busy ? 'Submitting for review...' : 'Evaluate & submit for review'} <ArrowUpRight size={16} /></button>{error && <p className="form-error">{error}</p>}</form><section className="results-column"><div className="ready-card"><Fingerprint size={25} /><strong>{result ? 'Evidence submitted for review' : 'Ready to fingerprint'}</strong><span>{result ? 'Administrator approval is required before blockchain anchoring.' : 'Reports are reviewed before they enter the immutable ledger.'}</span></div></section></section>;
}

export default function ModernApp() {
  const [user, setUser] = useState(null); const [view, setView] = useState('process'); const [records, setRecords] = useState([]); const authReady = useRef(!auth);
  const refresh = async () => { try { const response = await apiFetch('/api/blockchain/ledger'); if (response.ok) setRecords((await response.json()).records || []); } catch { setRecords([]); } };
  useEffect(() => { if (!auth) return undefined; return onAuthStateChanged(auth, (firebaseUser) => { authReady.current = true; setUser(firebaseUser?.email || null); }); }, []);
  useEffect(() => { if (authReady.current && auth && user === null) signOut(auth); }, [user]); useEffect(() => { if (user) refresh(); }, [user]);
  if (!user) return <ModernLogin />;
  const pages = [{ id: 'process', label: 'Process evidence', icon: FileUp }, { id: 'ledger', label: 'On-chain ledger', icon: Database }, { id: 'review', label: 'Approval queue', icon: ClipboardCheck }, { id: 'intelligence', label: 'Intelligence', icon: LineChart }]; const current = pages.find((page) => page.id === view);
  return <div className="app-shell"><aside><div className="brand"><div className="brand-icon"><ShieldAlert size={18} /></div><div>CTI / <b>ANCHOR</b><small>THREAT INTELLIGENCE</small></div></div><nav>{pages.map(({ id, label, icon: Icon }) => <button key={id} className={view === id ? 'active' : ''} onClick={() => setView(id)}><Icon size={17} /> {label}</button>)}</nav><div className="side-status"><span className="pulse" /> Sepolia network<br /><small>Approval required</small></div><button className="logout" onClick={() => setUser(null)}><LogOut size={15} /> Sign out</button></aside><main className="workspace"><header><div><div className="eyebrow">THREAT OPERATIONS / {view.toUpperCase()}</div><h2>{current.label}</h2></div><div className="profile"><span className="avatar">{user[0]}</span><span>{user}<small>Authenticated user</small></span></div></header>{view === 'process' ? <ProcessEvidencePage /> : <ReviewDashboard records={records} refresh={refresh} initialTab={view} />}</main></div>;
}
